version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Server/Dockerfile
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: LiveLinesClient/Dockerfile
